... -*- Mode: doctest -*-
... run: examples/framework/diary/diary.py

>>> from kiwi.ui.test.runner import runner
>>> runner.start()
>>> Diary = runner.waitopen("Diary")
>>> Diary.add.clicked()
>>> Diary.title.set_text("New title")
>>> Diary.title.set_text("Foobar")
>>> Diary.add.clicked()
>>> Diary.title.set_text("")
>>> Diary.title.set_text("New title")
>>> Diary.ObjectList.select_paths(['1'])
>>> Diary.title.set_text("Testing")
>>> Diary.title.set_text("")
>>> Diary.title.set_text("Foobar")
>>> Diary.ObjectList.select_paths(['0'])
>>> Diary.remove.clicked()
>>> Diary.ObjectList.select_paths([])
>>> Diary.title.set_text("")
>>> Diary.title.set_text("Testing")
>>> Diary.ObjectList.select_paths(['0'])
>>> Diary.period.clicked()
>>> Diary.evening.clicked()
>>> Diary.remove.clicked()
>>> Diary.ObjectList.select_paths([])
>>> Diary.delete()
>>> runner.waitclose("Diary")
>>> runner.quit()
