... -*- Mode: doctest -*-
... run: examples/validation/personalinformation.py

>>> from kiwi.ui.test.runner import runner
>>> Form = runner.waitopen("Form")
>>> Form.name.set_text("")
>>> Form.name.set_text("J")
>>> Form.name.set_text("Jo")
>>> Form.name.set_text("Joh")
>>> Form.name.set_text("Joha")
>>> Form.name.set_text("Johan")
>>> Form.age.set_text("")
>>> Form.age.set_text("  ")
>>> Form.age.set_text(" ")
>>> Form.age.set_text("1 ")
>>> Form.age.set_text("1")
>>> Form.age.set_text("12")
>>> Form.age.set_text("1")
>>> Form.age.set_text("1 ")
>>> Form.age.set_text(" ")
>>> Form.age.set_text("  ")
>>> Form.age.set_text(" ")
>>> Form.age.set_text("9 ")
>>> Form.age.set_text("9")
>>> Form.age.set_text("99")
>>> Form.GtkToggleButton.clicked()
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("  /  /    ")
>>> Form.ProxyEntry.set_text(" /  /    ")
>>> Form.ProxyEntry.set_text("/  /    ")
>>> Form.ProxyEntry.set_text("  /    ")
>>> Form.ProxyEntry.set_text(" /    ")
>>> Form.ProxyEntry.set_text("/    ")
>>> Form.ProxyEntry.set_text("    ")
>>> Form.ProxyEntry.set_text("   ")
>>> Form.ProxyEntry.set_text("  ")
>>> Form.ProxyEntry.set_text(" ")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("02/14/1969")
>>> Form.GtkToggleButton.clicked()
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("  /  /    ")
>>> Form.ProxyEntry.set_text(" /  /    ")
>>> Form.ProxyEntry.set_text("/  /    ")
>>> Form.ProxyEntry.set_text("  /    ")
>>> Form.ProxyEntry.set_text(" /    ")
>>> Form.ProxyEntry.set_text("/    ")
>>> Form.ProxyEntry.set_text("    ")
>>> Form.ProxyEntry.set_text("   ")
>>> Form.ProxyEntry.set_text("  ")
>>> Form.ProxyEntry.set_text(" ")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("02/13/1969")
>>> Form.height.set_text("")
>>> Form.height.set_text("1")
>>> Form.height.set_text("12")
>>> Form.height.set_text("123")
>>> Form.height.set_text("1234")
>>> Form.height.set_text("12345")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("87")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("88")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("89")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("90")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("91")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("92")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("93")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("92")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("91")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("90")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("89")
>>> Form.weight.set_text("")
>>> Form.weight.set_text("90")
>>> Form.height.set_text("")
>>> Form.height.set_text("1")
>>> Form.height.set_text("12")
>>> Form.age.set_text("")
>>> Form.age.set_text("  ")
>>> Form.age.set_text(" ")
>>> Form.age.set_text("1 ")
>>> Form.age.set_text("1")
>>> Form.age.set_text("12")
>>> Form.GtkToggleButton.clicked()
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Brazilian")
>>> Form.GtkToggleButton.clicked()
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Yankee")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Other")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Yankee")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Brazilian")
>>> Form.ProxyEntry.set_text("")
>>> Form.ProxyEntry.set_text("Yankee")
>>> Form.gender.select_item_by_label("Male")
>>> Form.gender.select_item_by_label("Female")
>>> Form.status_single.clicked()
>>> Form.status.clicked()
>>> Form.status.clicked()
>>> Form.status_single.clicked()
>>> Form.ok_btn.clicked()
>>> runner.quit()
