#
# Kiwi: a Framework and Enhanced Widgets for Python
#
# Copyright (C) 2005 Async Open Source
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307
# USA
# 
# Author(s): Johan Dahlin <jdahlin@async.com.br>
#         

from distutils.command.install_lib import install_lib
from distutils.dep_util import newer
from distutils.log import info
from fnmatch import fnmatch
import os

_TEMPLATE_HEADER = '''# Generated by setup.py do not modify
resources = {}
'''

class TemplateInstallLib(install_lib):
    # Overridable by subclass
    resources = {}
    
    def generate_template(self, resources={}):
        if not 'name' in resources:
            raise TypeError("resources in %r is missing name" % self)
        name = resources.pop('name')

        install = self.distribution.get_command_obj('install')
        prefix = install.prefix
        datadir = os.path.join(prefix, 'share', )

        filename = os.path.join(self.install_dir, name, '__installed__.py')
        self.mkpath(os.path.dirname(filename))
        
        fp = open(filename, 'w')
        fp.write(_TEMPLATE_HEADER)
        for name, value in resources.items():
            value = value.replace('$prefix', prefix)
            value = value.replace('$datadir', datadir)
            
            fp.write("resources['%s'] = '%s'\n" % (name, value))
        fp.close()
        
	return filename

    def install(self):
        template = self.generate_template(self.resources)
        return install_lib.install(self) + [template]

def listfiles(*dirs):
    dir, pattern = os.path.split(os.path.join(*dirs))
    return [os.path.join(dir, filename)
            for filename in os.listdir(os.path.abspath(dir))
                if filename[0] != '.' and fnmatch(filename, pattern)]

def compile_po_files(appname, dirname='locale'):
    data_files = []
    for po in listfiles('po', '*.po'):
        lang = os.path.basename(po[:-3])
        mo = os.path.join(dirname, lang, 'LC_MESSAGES', appname + '.mo')

        if not os.path.exists(mo) or newer(po, mo):
            directory = os.path.dirname(mo)
            if not os.path.exists(directory):
                info("creating %s" % directory)
                os.makedirs(directory)
            cmd = 'msgfmt -o %s %s' % (mo, po)
            info('compiling %s -> %s' % (po, mo))
            if os.system(cmd) != 0:
                raise SystemExit("Error while running msgfmt")
        dest = os.path.dirname(os.path.join('share', mo))
        data_files.append((dest, [mo]))

    return data_files
